name: Build and Deploy Beta Package on PR
on:
  pull_request:

jobs:
  build:
    uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
    with:
      package_folder: output
      revision: ${{github.run_number}}
    secrets: inherit

  coverage:
    needs: build
    uses: flexbase-eng/.github/.github/workflows/typescript.sonarcloud.yml@main
    with:
      project_key: flexbase-eng_${{ github.event.repository.name }}
    secrets: inherit

  publish:
    if: github.repository != 'flexbase-eng/template-typescript-package'
    needs: coverage
    uses: flexbase-eng/.github/.github/workflows/typescript.publish.npm.yml@main
    with:
      tag: beta
    secrets: inherit
