name: Build and Deploy Package
on:
  push:
    branches: main

jobs:
  build:
    uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
    with:
      package_folder: output
    secrets: inherit

  coverage:
    needs: build
    uses: flexbase-eng/.github/.github/workflows/typescript.sonarcloud.yml@main
    with:
      project_key: flexbase-eng_${{ github.event.repository.name }}
    secrets: inherit
  
  publish:
    if: github.repository != 'flexbase-eng/template-typescript-package'
    needs: coverage
    uses: flexbase-eng/.github/.github/workflows/typescript.publish.npm.yml@main
    secrets: inherit
