name: Pull Request
on:
  pull_request:

jobs:
  pr:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      node_version: '20'
      environment: 'development'
      build_cache_key: build-cache-${{ github.sha }}
      tag: 'beta'
