name: Unit Test
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      build_cache_key:
        required: true
        type: string
      coverage_artifact_folder:
        required: false
        type: string
        default: 'coverage/lcov.info'
      coverage_artifact_name:
        required: false
        type: string
        default: 'code-coverage-report'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      CLI_TEST: pnpm turbo test:ci
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4' # needed by google auth
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: pnpm

      - name: Retrieve build cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ./*
          key: ${{ inputs.build_cache_key }}
          fail-on-cache-miss: true

      - name: Retrieve turbo cache
        uses: actions/cache/restore@v4
        with:
          path: ./.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: ${{ runner.os }}-turbo-

      - name: Run tests
        run: ${{ env.CLI_TEST }}

      - name: Upload turbo cache
        uses: actions/cache@v4
        with:
          path: ./.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}

      - name: Upload coverage artifacts
        if: ${{ inputs.coverage_artifact_folder != ''}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ${{ inputs.coverage_artifact_folder }}
          retention-days: 1
